### PR TITLE
Feature/exit cli on unsuccess

### PR DESCRIPTION
**Pull request by ymekuria**
This pr adds functionality to allow the CLI to exit when the current step is unsuccessful for a better ux. This was accomplished by:
- Calling the SnarkyJs  async shutdown function on error cases
- Adding code to exit the process on the error catch block of the step helper function

### CODE REVIEW

**Comment by mitschabaude** [comment]
This closes #154 and #161 right?

**Comment by ymekuria** [comment]
> This closes #154 and #161 right?

Yeah it does. I will connect those issues.

**Review by jasongitmail — CHANGES_REQUESTED** [review]
Looks like a good approach! But shutdown isn't needed until after SnarkyJS is imported via:
```
  let { isReady, shutdown, PrivateKey, addCachedAccount, Mina } = await import(
    `${DIR}/node_modules/snarkyjs/dist/server/index.mjs`
  );
```

So we could clean it up by importing SnarkyJS lower in the file around Line #212

Then we can remove shutdown() calls before that on 183, 195, 209

_Update: Disregard. It worked this morning, but maybe I missed something in my testing since I was hurrying into a meeting, because now I’m seeing the behavior that you saw @ymekuria_

**Comment by mitschabaude** [comment]
+1 to @jasongitmail's suggestion, I think the first time snarkyjs is needed is at this line:
```js
let zkAppPrivateKey = PrivateKey.fromBase58(privateKey); //  The private key of the zkApp
```

**Review by jasongitmail — APPROVED** [review]

**Review by MartinMinkov — APPROVED** [review]

**Pull request merged**
