### PR TITLE
Add app directory option for Next.js

### PR DESCRIPTION
**Pull request by feyyum**
When using Next.js, some users may want to take advantage of the app directory option. With this update, they will be relieved of the extra workload.

### CODE REVIEW

**Comment by shimkiv** [comment]
Hey @feyyum thank you for contribution!
Please don't forget to also reflect introduced change in tests.

**Comment by ymekuria** [comment]
Thanks for adding this @feyyum . This has been on the roadmap to add but other things have taken priority. I'll take a look at your PR soon.

**Comment by feyyum** [comment]
@shimkiv  and @ymekuria, thanks for your feedbacks. I will review and add tests and features.

**Comment by ymekuria** [comment]
Sounds good @feyyum. Upgrading to v14 is also on our roadmap. Let me know if you need help or run into any issues.

**Pull request closed without merging**
