### PR TITLE
Fix for Nuxt projects and NextJS getting stated page text.

### LINKED ISSUE #449: Impossible to generate Nuxt project
```shell
~/projects/o1/zkapp-cli   e2e-tests ±  zk project  deploy-me
✔ Create an accompanying UI project too? · nuxt
Nuxi 3.4.0                                                                                                                                  7:04:11 PM
✨ Nuxt project is created with v3 template. Next steps:                                                                                    7:04:12 PM
 › cd ui                                                                                                                                    7:04:12 PM
 › Install dependencies with npm install or yarn install or pnpm install                                                                    7:04:12 PM
 › Start development server with npm run dev or yarn dev or pnpm run dev                                                                    7:04:12 PM
✔ UI: Set up project
✖ UI: NPM install
 ✘  ~/projects/o1/zkapp-cli   e2e-tests ±  cd deploy-me/
 ~/projects/o1/zkapp-cli/deploy-me   e2e-tests ±  ll
total 0
drwxr-xr-x   3 serhii  staff   96 Jul  7 19:04 .
drwxr-xr-x  29 serhii  staff  928 Jul  7 19:04 ..
drwxrwxr-x  16 serhii  staff  512 Jul  7 19:04 ui
 ~/projects/o1/zkapp-cli/deploy-me   e2e-tests ±  cd ui
 ~/projects/o1/zkapp-cli/deploy-me/ui   e2e-tests ±  npm install

> postinstall
> nuxt prepare

Nuxi 3.6.2                                                                                                                                  7:05:16 PM

 ERROR  ParseError: Unexpected token, expected ","                                                                                          7:05:17 PM
 /Users/shymkiv/projects/o1/zkapp-cli/deploy-me/ui/nuxt.config.ts:12:2

  nuxt.config.ts:12:2
  at resolveConfig (node_modules/c12/dist/index.mjs:280:24)
  at loadConfig (node_modules/c12/dist/index.mjs:116:40)
  at async loadNuxtConfig (node_modules/@nuxt/kit/dist/index.mjs:2483:18)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:3269:19)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2537:19)
  at async Object.invoke (node_modules/nuxi/dist/chunks/prepare.mjs:31:18)
  at async _main (node_modules/nuxi/dist/cli.mjs:49:20)

npm ERR! code 1
npm ERR! path /Users/shymkiv/projects/o1/zkapp-cli/deploy-me/ui
npm ERR! command failed
npm ERR! command sh -c nuxt prepare

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shymkiv/.npm/_logs/2023-07-07T16_05_15_030Z-debug-0.log
 ✘  ~/projects/o1/zkapp-cli/deploy-me/ui   e2e-tests ±  zk -v
0.10.1
```

### LINKED ISSUE #450: Update NextJS welcome page getting started text
Users will always see `Get started by editing src/pages/index.tsx` regardless of selected language in use (JS or TS). It will be good to show users `.../index.(js|tsx)`.

### PR DESCRIPTION
**Pull request by shimkiv**
Closes #449
Closes #450

### CODE REVIEW

**Review by ymekuria — APPROVED** [review]
LGTM! Thanks for doing this. Can you bump the version and update the changelog?

**Comment by shimkiv** [comment]
> LGTM! Thanks for doing this. Can you bump the version and update the changelog?

Thank you! I addressed your request but left new release version date as `TBA` (`## [0.10.2] - TBA`).

**Comment by ymekuria** [comment]
> > LGTM! Thanks for doing this. Can you bump the version and update the changelog?
> 
> Thank you! I addressed your request but left new release version date as `TBA` (`## [0.10.2] - TBA`).

Thanks @shimkiv! The release date is whenever this PR is merged. You can put today as the date and we can merge it.

**Review by ymekuria — APPROVED** [review]

**Comment by shimkiv** [comment]
@ymekuria Done!
Thank you.

**Pull request merged**
