### PR TITLE
fix sudoku example test errors

### PR DESCRIPTION
**Pull request by MeerKatDev**
Minimal changes to make tests for sudoku work, as in issue #311

### CODE REVIEW

**Comment by MeerKatDev** [comment]
I wonder if instead of initialize... there should be 
```
  @method update(sudokuInstance: Sudoku) {
```
to manually initialize the sudoku hash.

**Comment by mitschabaude** [comment]
I actually want to make it work with `init()`, but I think it'll need a change to the CLI's deploy logic

**Comment by MeerKatDev** [comment]
but `init()` does not take arguments, how do you pass the `hash()` from `sudokuInstance` ?

**Comment by mitschabaude** [comment]
thanks for making this PR and highlighting what needs to be fixed! I ended up inlcuding this as part a larger PR (https://github.com/o1-labs/zkapp-cli/pull/315), so closing this one

**Pull request closed without merging**
