### PR TITLE
Test generated projects with UI as part of the Nightly testing iterations.

### LINKED ISSUE #478: Add in-browser e2e tests for projects generated with UI

### PR DESCRIPTION
**Pull request by shimkiv**
Closes #478

### CODE REVIEW

**Review by ymekuria — APPROVED** [review]
LGTM.

**Comment by garwalsh** [comment]
Closes #478

**Comment by shimkiv** [comment]
Two issues exist but they should not impact nightly tests on CI yet it will be good to have fixes.
- https://github.com/o1-labs/zkapp-cli/issues/558
- https://github.com/o1-labs/zkapp-cli/issues/559

**Comment by shimkiv** [comment]
Nightly [passed](https://github.com/o1-labs/zkapp-cli/actions/runs/7607944920), so I'll merge it.

**Pull request merged**
