### PR TITLE
Update TicTacToe example to deploy to Berkeley

### LINKED ISSUE #186: Confirm TicTacToe example builds, tests pass, & deploys to QANet

### PR DESCRIPTION
**Pull request by MartinMinkov**
**Description**
This fixes #186

Updates the `TicTacToe` example to deploy successfully on the Berkeley network. This was done by splitting up the example into 2 separate files, one being `index.ts` and the other being `tictactoe.ts`

`index.ts` holds the smart contract definition and the other related classes it needs to be functional and deployed. 

`tictactoe.ts` holds the logic to run the smart contract locally. This was previously stuffed into `index.ts` and was being run when deploying. We move all the logic to run the smart contract locally in it's own file to separate concerns. 

**Note**: This means that to run the smart contract locally, users will need to run `npm run build && node build/src/tictactoe.js` instead of specifying `build/src/index.js`

**Tested**
Deployed to Berkeley on the following account: https://berkeley.minaexplorer.com/wallet/B62qoCzCw1dhTYAVCMqPdGhQSjAB7rZxm1n9V4UxB8oC7qVVM1MS85g

**Open Questions**
Do we want to add some comments at the top of each file to explain why they are separated and how to run them? Might introduce some confusion for the user since there's 2 JavaScript files that are in the `build` directory. Perhaps we can rename `tictactoe.js` to something more relatable to being run local?

### CODE REVIEW

**Comment by jasongitmail** [comment]
I like the solution to separate these. That's a definite improvement. 

But what if we flipped the file names, so that `tictactoe.ts` contains the smart contract with this corresponding name (it also following the pattern we show devs to use for their own smart contracts) and then `index.ts` would be the entry point to run it locally? I haven't thought through all the aspects of this if there are any gotchas, but it feels right on the surface.

> Do we want to add some comments at the top of each file to explain why they are separated and how to run them? 

This seems useful +1

**Comment by MartinMinkov** [comment]
> I like the solution to separate these. That's a definite improvement.
> 
> But what if we flipped the file names, so that `tictactoe.ts` contains the smart contract with this corresponding name (it also following the pattern we show devs to use for their own smart contracts) and then `index.ts` would be the entry point to run it locally? I haven't thought through all the aspects of this if there are any gotchas, but it feels right on the surface.
> 
> > Do we want to add some comments at the top of each file to explain why they are separated and how to run them?
> 
> This seems useful +1

Sounds good! I'll swap the file names and add some comments at the top of each file for ease of the user.

**Review by jasongitmail — APPROVED** [review]
Looks great!

**Comment by jasongitmail** [comment]
@MartinMinkov Do you want to bump the CLI version on this so it redeploys please?

**Pull request merged**
